# Generated by Django 4.2.2 on 2023-06-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_program_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='https://fakeimg.pl/200x150', upload_to='event/images/'),
        ),
    ]
