# Generated by Django 4.2.2 on 2023-06-12 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_event_ticket_price_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
